
blueprint:
  name: "IKEA Time Lights - ULTRA SIMPLE"
  description: "Day/night lights by fixed time (20-6). Expand later."
  domain: automation
  input:
    remote:
      name: "ZHA Device"
      selector:
        device:
          integration: zha
    day_light:
      name: "Day light"
      selector:
        entity:
          domain: light
    night_light:
      name: "Night light"
      selector:
        entity:
          domain: light
    speed:
      name: "Speed"
      selector:
        number:
          min: 100
          max: 1000
          step: 100
      default: 500

mode: restart

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'on' }}"
        sequence:
          - if:
              - condition: or
                conditions:
                  - "{{ now().hour >= 20 }}"
                  - "{{ now().hour < 6 }}"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input night_light
            else:
              - service: light.turn_on
                target:
                  entity_id: !input day_light
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'off' }}"
        sequence:
          - if:
              - condition: or
                conditions:
                  - "{{ now().hour >= 20 }}"
                  - "{{ now().hour < 6 }}"
            then:
              - service: light.turn_off
                target:
                  entity_id: !input night_light
            else:
              - service: light.turn_off
                target:
                  entity_id: !input day_light
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'move_with_on_off' }}"
        sequence:
          - repeat:
              sequence:
                - if:
                    - condition: or
                      conditions:
                        - "{{ now().hour >= 20 }}"
                        - "{{ now().hour < 6 }}"
                  then:
                    - service: light.turn_on
                      target:
                        entity_id: !input night_light
                      data:
                        brightness_step_pct: 10
                  else:
                    - service: light.turn_on
                      target:
                        entity_id: !input day_light
                      data:
                        brightness_step_pct: 10
                - delay:
                    milliseconds: !input speed
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'move' }}"
        sequence:
          - repeat:
              sequence:
                - if:
                    - condition: or
                      conditions:
                        - "{{ now().hour >= 20 }}"
                        - "{{ now().hour < 6 }}"
                  then:
                    - service: light.turn_on
                      target:
                        entity_id: !input night_light
                      data:
                        brightness_step_pct: -10
                  else:
                    - service: light.turn_on
                      target:
                        entity_id: !input day_light
                      data:
                        brightness_step_pct: -10
                - delay:
                    milliseconds: !input speed

variables:
  dummy: "dummy"
