
blueprint:
  name: "IKEA TRADFRI Day/Night Lights - WORKING"
  description: "ON/OFF switches day/night light by time. Universal ZHA."
  domain: automation
  input:
    remote:
      name: "ZHA Device (IKEA switch)"
      description: "Vyber své IKEA tlačítko - objeví se mezi ZHA devices."
      selector:
        device:
          integration: zha
          multiple: false
    day_light:
      name: "Denní světlo (group OK)"
      selector:
        entity:
          domain: light
          multiple: false
    night_light:
      name: "Noční světlo"
      selector:
        entity:
          domain: light
          multiple: false
    speed:
      name: "Dim speed (ms)"
      selector:
        number:
          min: 100
          max: 1000
          step: 100
          mode: slider
      default: 500
    night_start:
      name: "Noční režim OD (např. 20:00)"
      selector:
        time:
      default: "20:00:00"
    night_end:
      name: "Noční režim DO (např. 06:00)"
      selector:
        time:
      default: "06:00:00"

mode: restart
max_exceeded: silent

variables:
  transition: "{{ (!input speed / 1000) | float(0) }}"

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - choose:
      # ON
      - conditions:
          - "{{ trigger.event.data.command == 'on' }}"
        sequence:
          - if:
              - condition: template
                value_template: >
                  {% set now_h = now().hour %}
                  {% set now_m = now().minute %}
                  {% set now_total = now_h * 60 + now_m %}
                  {% set start_h = states('input_datetime.night_start') | int(0) // 10000 %}
                  {% set start_m = (states('input_datetime.night_start') | int(0) % 10000) // 100 %}
                  {% set end_h = states('input_datetime.night_end') | int(0) // 10000 %}
                  {% set end_m = (states('input_datetime.night_end') | int(0) % 10000) // 100 %}
                  {% set start_total = start_h * 60 + start_m %}
                  {% set end_total = end_h * 60 + end_m %}
                  {{ (start_total > end_total and (now_total >= start_total or now_total <= end_total)) or (start_total <= end_total and now_total >= start_total and now_total <= end_total) }}
            then:
              - service: light.turn_on
                target:
                  entity_id: !input night_light
                data:
                  transition: "{{ transition }}"
            else:
              - service: light.turn_on
                target:
                  entity_id: !input day_light
                data:
                  transition: "{{ transition }}"
      # OFF
      - conditions:
          - "{{ trigger.event.data.command == 'off' }}"
        sequence:
          - if:
              - condition: template
                value_template: >
                  {% set now_h = now().hour %}
                  {% set now_m = now().minute %}
                  {% set now_total = now_h * 60 + now_m %}
                  {% set start_h = states('input_datetime.night_start') | int(0) // 10000 %}
                  {% set start_m = (states('input_datetime.night_start') | int(0) % 10000) // 100 %}
                  {% set end_h = states('input_datetime.night_end') | int(0) // 10000 %}
                  {% set end_m = (states('input_datetime.night_end') | int(0) % 10000) // 100 %}
                  {% set start_total = start_h * 60 + start_m %}
                  {% set end_total = end_h * 60 + end_m %}
                  {{ (start_total > end_total and (now_total >= start_total or now_total <= end_total)) or (start_total <= end_total and now_total >= start_total and now_total <= end_total) }}
            then:
              - service: light.turn_off
                target:
                  entity_id: !input night_light
                data:
                  transition: "{{ transition }}"
            else:
              - service: light.turn_off
                target:
                  entity_id: !input day_light
                data:
                  transition: "{{ transition }}"
      # BRIGHTNESS UP (hold ON)
      - conditions:
          - "{{ trigger.event.data.command == 'move_with_on_off' }}"
        sequence:
          - repeat:
              sequence:
                - if:
                    - condition: template
                      value_template: >
                        {% set now_h = now().hour %}
                        {% set now_m = now().minute %}
                        {% set now_total = now_h * 60 + now_m %}
                        {% set start_h = states('input_datetime.night_start') | int(0) // 10000 %}
                        {% set start_m = (states('input_datetime.night_start') | int(0) % 10000) // 100 %}
                        {% set end_h = states('input_datetime.night_end') | int(0) // 10000 %}
                        {% set end_m = (states('input_datetime.night_end') | int(0) % 10000) // 100 %}
                        {% set start_total = start_h * 60 + start_m %}
                        {% set end_total = end_h * 60 + end_m %}
                        {{ (start_total > end_total and (now_total >= start_total or now_total <= end_total)) or (start_total <= end_total and now_total >= start_total and now_total <= end_total) }}
                  then:
                    - service: light.turn_on
                      target:
                        entity_id: !input night_light
                      data:
                        brightness_step_pct: 10
                        transition: "{{ transition }}"
                  else:
                    - service: light.turn_on
                      target:
                        entity_id: !input day_light
                      data:
                        brightness_step_pct: 10
                        transition: "{{ transition }}"
                - delay:
                    milliseconds: !input speed
      # BRIGHTNESS DOWN (hold OFF)
      - conditions:
          - "{{ trigger.event.data.command == 'move' }}"
        sequence:
          - repeat:
              sequence:
                - if:
                    - condition: template
                      value_template: >
                        {% set now_h = now().hour %}
                        {% set now_m = now().minute %}
                        {% set now_total = now_h * 60 + now_m %}
                        {% set start_h = states('input_datetime.night_start') | int(0) // 10000 %}
                        {% set start_m = (states('input_datetime.night_start') | int(0) % 10000) // 100 %}
                        {% set end_h = states('input_datetime.night_end') | int(0) // 10000 %}
                        {% set end_m = (states('input_datetime.night_end') | int(0) % 10000) // 100 %}
                        {% set start_total = start_h * 60 + start_m %}
                        {% set end_total = end_h * 60 + end_m %}
                        {{ (start_total > end_total and (now_total >= start_total or now_total <= end_total)) or (start_total <= end_total and now_total >= start_total and now_total <= end_total) }}
                  then:
                    - service: light.turn_on
                      target:
                        entity_id: !input night_light
                      data:
                        brightness_step_pct: -10
                        transition: "{{ transition }}"
                  else:
                    - service: light.turn_on
                      target:
                        entity_id: !input day_light
                      data:
                        brightness_step_pct: -10
                        transition: "{{ transition }}"
                - delay:
                    milliseconds: !input speed
    default: []
