
blueprint:
  name: "IKEA TRADFRI Time Lights - WORKING"
  description: "ON/OFF switches day/night light by time range. Uses minutes of day."
  domain: automation
  input:
    remote:
      name: Remote
      selector:
        device:
          integration: zha
          manufacturer: IKEA
          model: "TRADFRI on/off switch"
    day_light:
      name: Day light
      selector:
        entity:
          domain: light
    night_light:
      name: Night light
      selector:
        entity:
          domain: light
    speed:
      name: Dim speed (ms)
      default: 500
      selector:
        number:
          min: 100
          max: 1000
          step: 100
          mode: slider
    night_start:
      name: Night start
      selector:
        time:
      default: "20:00:00"
    night_end:
      name: Night end
      selector:
        time:
      default: "06:00:00"

mode: restart

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      transition: "{{ (!input speed / 1000) | float }}"
      now_minutes: "{{ now().hour * 60 + now().minute }}"
      start_minutes: "{{ (states('input_datetime.night_start') | timestamp_custom('%H:%M') | strptime('%H:%M') | timestamp_custom('%H') | int * 60 + states('input_datetime.night_start') | timestamp_custom('%M') | int }}"
      end_minutes: "{{ (states('input_datetime.night_end') | timestamp_custom('%H:%M') | strptime('%H:%M') | timestamp_custom('%H') | int * 60 + states('input_datetime.night_end') | timestamp_custom('%M') | int }}"
      is_night: >
        {% if start_minutes > end_minutes %}
          {{ now_minutes >= start_minutes or now_minutes <= end_minutes }}
        {% else %}
          {{ now_minutes >= start_minutes and now_minutes <= end_minutes }}
        {% endif %}

  - choose:
      - conditions:
          - "{{ trigger.event.data.command == 'on' }}"
        sequence:
          - service: "{{ 'light.turn_on' if is_night else 'light.turn_on' }}"
            target:
              entity_id: "{{ night_light if is_night else day_light }}"
            data:
              transition: "{{ transition }}"

      - conditions:
          - "{{ trigger.event.data.command == 'off' }}"
        sequence:
          - service: "{{ 'light.turn_off' if is_night else 'light.turn_off' }}"
            target:
              entity_id: "{{ night_light if is_night else day_light }}"
            data:
              transition: "{{ transition }}"

      - conditions:
          - "{{ trigger.event.data.command == 'move_with_on_off' }}"
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ night_light if is_night else day_light }}"
                  data:
                    brightness_step_pct: 10
                    transition: "{{ transition }}"
                - delay:
                    milliseconds: !input speed

      - conditions:
          - "{{ trigger.event.data.command == 'move' }}"
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ night_light if is_night else day_light }}"
                  data:
                    brightness_step_pct: -10
                    transition: "{{ transition }}"
                - delay:
                    milliseconds: !input speed

    default: []
