blueprint:

  source_url: https://github.com/metbril/home-assistant-blueprints/blob/main/automation/zha_ikea_tradfri_2button_onoff_brightness.yaml

  name: "ZHA - IKEA TRADFRI - 2 Button Remote - On/Off and Brightness (Night Mode, Optional, Double Click)"

  description: IKEA TRADFRI 2 button remote s volitelným nočním režimem a podporou dvojkliku.

  domain: automation

input:

  remote:
    name: IKEA TRADFRI remote control
    selector:
      device:
        integration: zha
        manufacturer: IKEA of Sweden
        model: TRADFRI on/off switch

  light:
    name: Day light
    description: Light used outside night hours
    selector:
      entity:
        domain: light

  night_light:
    name: Night light
    description: Light used during night hours (optional)
    selector:
      entity:
        domain: light
    default: []

  use_night_mode:
    name: Use night mode
    description: Enable different light for night hours and night timing.
    selector:
      boolean:
    default: false

  night_start:
    name: Night mode start
    description: Time when night mode starts
    selector:
      time:
    default: "20:00:00"

  night_end:
    name: Night mode end
    description: Time when night mode ends
    selector:
      time:
    default: "06:00:00"

  speed:
    name: Speed
    selector:
      number:
        min: 100
        max: 1000
        step: 100
        unit_of_measurement: milliseconds
        mode: slider
    default: 500

  on_double_click_action:
    name: ON double click action
    description: Action to run on ON double click
    default: []
    selector:
      action:

  off_double_click_action:
    name: OFF double click action
    description: Action to run on OFF double click
    default: []
    selector:
      action:

mode: restart
max_exceeded: silent

variables:
  var_speed: !input speed
  transition_speed: "{{ (var_speed / 1000) | float }}"
  day_light: !input light
  night_light_var: !input night_light
  night_start: !input night_start
  night_end: !input night_end
  use_night_mode: !input use_night_mode

  is_night: >
    {% set now_t = now().strftime('%H:%M:%S') %}
    {% if night_start < night_end %}
      {{ night_start <= now_t < night_end }}
    {% else %}
      {{ now_t >= night_start or now_t < night_end }}
    {% endif %}

  target_light: >
    {% if use_night_mode and night_light_var != [] %}
      {{ night_light_var if is_night else day_light }}
    {% else %}
      {{ day_light }}
    {% endif %}

trigger:
  - platform: event
    event_type: zha_event
    event_
      device_id: !input remote

action:
  - choose:

      # === ON (single press) ===
      - conditions: "{{ trigger.event.data.command == 'on' and trigger.event.data.args is not defined }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ target_light }}"
            
              transition: "{{ transition_speed }}"

      # === ON double click ===
      # pro TRÅDFRI bývá command 'on' + args: [2] nebo podobně, případně 'step_with_on_off'
      - conditions: >
          {{ trigger.event.data.command == 'on' and
             trigger.event.data.args is defined and
             (trigger.event.data.args | string | contains('2')) }}
        sequence: !input on_double_click_action

      # === BRIGHTNESS UP (hold ON) ===
      - conditions: "{{ trigger.event.data.command == 'move_with_on_off' }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ target_light }}"
                  
                    brightness_step_pct: 10
                    transition: "{{ transition_speed }}"
                - delay:
                    milliseconds: !input speed

      # === OFF (single press) ===
      - conditions: "{{ trigger.event.data.command == 'off' and trigger.event.data.args is not defined }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ target_light }}"
            
              transition: "{{ transition_speed }}"

      # === OFF double click ===
      # obdobná logika jako pro ON double click, uprav si podle skutečných args z debuggeru
      - conditions: >
          {{ trigger.event.data.command == 'off' and
             trigger.event.data.args is defined and
             (trigger.event.data.args | string | contains('2')) }}
        sequence: !input off_double_click_action

      # === BRIGHTNESS DOWN (hold OFF, min 1 %) ===
      - conditions: "{{ trigger.event.data.command == 'move' }}"
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ target_light }}"
                  
                    # snižuj jas jen pokud je > 1 %
                    brightness_step: >
                      {% set entity = target_light %}
                      {% set b = state_attr(entity, 'brightness') | int(0) %}
                      {% if b <= 3 %}
                        0
                      {% else %}
                        - (b * 0.1) | int
                      {% endif %}
                    transition: "{{ transition_speed }}"
                - delay:
                    milliseconds: !input speed
