blueprint:
  name: "ZHA - IKEA TRADFRI - 2 Button Remote - Enhanced"
  description: IKEA TRADFRI 2 button remote s volitelným nočním režimem a dvojklikem.
  source_url: https://github.com/metbril/home-assistant-blueprints/blob/main/automation/zha_ikea_tradfri_2button_onoff_brightness.yaml
  domain: automation

input:
  remote:
    name: IKEA TRADFRI remote
    selector:
      device:
        integration: zha
        manufacturer: IKEA of Sweden
        model: TRADFRI on/off switch
  light:
    name: Day light
    selector:
      entity:
        domain: light
  night_light:
    name: Night light
    selector:
      entity:
        domain: light
    default: []
  use_night_mode:
    name: Use night mode
    selector:
      boolean:
    default: false
  night_start:
    name: Night start
    selector:
      time:
    default: "20:00:00"
  night_end:
    name: Night end
    selector:
      time:
    default: "06:00:00"
  speed:
    name: Speed (ms)
    selector:
      number:
        min: 100
        max: 1000
        step: 100
        mode: slider
    default: 500
  on_double_action:
    name: ON double click
    selector:
      action: {}
    default: []
  off_double_action:
    name: OFF double click
    selector:
      action: {}
    default: []

variables:
  speed: !input speed
  trans: "{{ (speed / 1000) | float(0.5) }}"
  day_light: !input light
  night_light: !input night_light
  use_night: !input use_night_mode
  night_start: !input night_start
  night_end: !input night_end
  is_night: >
    {% set now = now().strftime('%H:%M:%S') %}
    {{ (night_start <= now <= night_end) if night_start <= night_end else (now >= night_start or now <= night_end) }}
  target: >
    {{ night_light if use_night and is_night and night_light else day_light }}

trigger:
- platform: event
  event_type: zha_event
  event_
    device_id: !input remote

action:
- choose:
  - conditions:
    - condition: template
      value_template: "{{ trigger.event.data.command == 'on' }}"
    sequence:
    - choose:
      - conditions:
        - condition: template
          value_template: "{{ trigger.event.data.args is defined }}"
        sequence: !input on_double_action
      - sequence:
        - service: light.turn_on
          target:
            entity_id: "{{ target }}"
          
            transition: "{{ trans }}"
  - conditions:
    - condition: template
      value_template: "{{ trigger.event.data.command == 'move_with_on_off' }}"
    sequence:
    - repeat:
        sequence:
        - service: light.turn_on
          target:
            entity_id: "{{ target }}"
          
            brightness_step_pct: 10
            transition: "{{ trans }}"
        - delay: "{{ '00:00:{{ speed }}' | timestamp_custom('%H:%M:%S.%f')[:-3] }}"
  - conditions:
    - condition: template
      value_template: "{{ trigger.event.data.command == 'off' }}"
    sequence:
    - choose:
      - conditions:
        - condition: template
          value_template: "{{ trigger.event.data.args is defined }}"
        sequence: !input off_double_action
      - sequence:
        - service: light.turn_off
          target:
            entity_id: "{{ target }}"
          
            transition: "{{ trans }}"
  - conditions:
    - condition: template
      value_template: "{{ trigger.event.data.command == 'move' }}"
    sequence:
    - repeat:
        sequence:
        - service: light.turn_on
          target:
            entity_id: "{{ target }}"
          
            brightness_step_pct: >
              {% set b = state_attr(target, 'brightness') | default(255) | int %}
              {{ 0 if b <= 3 else -10 }}
            transition: "{{ trans }}"
        - delay: "{{ '00:00:{{ speed }}' | timestamp_custom('%H:%M:%S.%f')[:-3] }}"

mode: restart
max_exceeded: silent
